# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yY7p1kJxcxu9hbTnPhCjMVAKppZVmccP
"""

"""
DiRAMotif — RNA-Binding Protein Motif Discovery Pipeline
==========================================================
This pipeline discovers candidate RNA-binding protein (RBP) motifs from
CLIP-seq derived RNA sequences. It combines k-mer frequency features, a
Dirichlet-prior Variational Autoencoder (VAE), and biologically informed
post-processing (enrichment, accessibility, and centrality scoring) to
produce ranked motif candidates and position weight matrices (PWMs).

Key methodological notes:
  - Position weight matrices are built from non-overlapping motif
    occurrences, selected greedily by minimum Hamming distance, and
    restricted to a central window of each peak sequence to reduce
    edge noise.
  - Pseudocounts scale with the number of observed occurrences rather
    than using a fixed value, which avoids over-smoothing PWMs built
    from a small number of sites.
  - Motif comparison against reference databases (e.g., ATtRACT) is
    performed with Tomtom, using empirical background nucleotide
    frequencies (rather than a uniform assumption) and a minimum
    overlap constraint proportional to motif length.
"""

import os
import csv
import glob
import json
import random
import shutil
import warnings
import subprocess
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

import matplotlib.pyplot as plt
import seaborn as sns

from Bio import SeqIO
from scipy.stats import fisher_exact
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
from statsmodels.stats.multitest import fdrcorrection

import RNA  # ViennaRNA package

warnings.filterwarnings('ignore')
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {DEVICE}")

# ============================================================================
# Configuration
# ============================================================================
DEFAULT_DATA_DIR = "/content/drive/dataset"
TRAIN_SUFFIX = "_train.fasta"
TEST_SUFFIX = "_test.fasta"
ICSHAPE_SUFFIX = "_icshape.json"

MIN_REAL_NEGATIVES_FOR_BACKGROUND = 200
MAX_ICSHAPE_NULL_FRACTION = 0.5

# Dropout rate used in the VAE architecture
DROPOUT_RATE = 0.2

# PWM construction parameters
PWM_MAX_MISMATCHES = 1
PWM_PSEUDOCOUNT_SCALE = 0.5          # relative pseudocount scaling factor (not an absolute value)
PWM_MIN_PSEUDOCOUNT = 0.25           # minimum pseudocount applied even for very low occurrence counts
PWM_CENTER_WINDOW_FRACTION = 0.6     # only the central 60% of each peak sequence is considered
PWM_MIN_INFO_CONTENT = None          # e.g. 0.5 to filter out low-quality motifs;
                                      # None = no filtering (still computed for reporting)

# Tomtom parameters
TOMTOM_MIN_OVERLAP = None            # None = computed automatically as max(k-1, 4)
TOMTOM_EVALUE_THRESH = 10.0

NUC_TO_IDX = {'A': 0, 'C': 1, 'G': 2, 'U': 3}


# ============================================================================
# Section 1: Core k-mer utilities and FASTA loading
# ============================================================================

def count_kmers_rna(sequence, k=6):
    sequence = sequence.replace('T', 'U').replace('t', 'u').upper()
    valid_chars = set('ACGU')
    sequence = ''.join([c for c in sequence if c in valid_chars])
    kmer_counts = Counter()
    for i in range(len(sequence) - k + 1):
        kmer = sequence[i:i + k]
        if 'N' not in kmer and len(kmer) == k:
            kmer_counts[kmer] += 1
    return kmer_counts


def load_fasta_records(fasta_file):
    records = []
    for record in SeqIO.parse(fasta_file, "fasta"):
        records.append((record.id, str(record.seq)))
    return records


def load_fasta_sequences(fasta_file):
    return [seq for _, seq in load_fasta_records(fasta_file)]


def load_icshape_scores(json_path):
    if json_path is None or not os.path.exists(json_path):
        return {}
    try:
        with open(json_path, "r") as f:
            data = json.load(f)
        return data
    except Exception as e:
        print(f"  Warning: failed to read icSHAPE file ({json_path}): {e}")
        return {}


def extract_rna_kmer_features_with_shared_dict(sequences, k, kmer_dict=None):
    build_dict = kmer_dict is None
    if build_dict:
        kmer_dict = {}

    all_kmer_counts = []
    for sequence in sequences:
        kmer_counts = count_kmers_rna(sequence, k=k)
        all_kmer_counts.append(kmer_counts)
        if build_dict:
            for kmer in kmer_counts:
                if kmer not in kmer_dict:
                    kmer_dict[kmer] = len(kmer_dict)

    feature_matrix = np.zeros((len(sequences), len(kmer_dict)), dtype=np.float32)
    for i, kmer_counts in enumerate(all_kmer_counts):
        for kmer, count in kmer_counts.items():
            if kmer in kmer_dict:
                feature_matrix[i, kmer_dict[kmer]] = count

    return feature_matrix, kmer_dict


class RNADataset(Dataset):
    def __init__(self, X):
        self.X = X.astype(np.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return torch.from_numpy(self.X[idx])


def check_sequence_length_diagnostics(fasta_file):
    lengths = [len(seq) for seq in load_fasta_sequences(fasta_file)]
    if not lengths:
        print(f"  Warning: no sequences found in {fasta_file}.")
        return None
    length_counts = Counter(lengths)
    most_common_len, most_common_n = length_counts.most_common(1)[0]
    report = {
        'file': fasta_file,
        'n_sequences': len(lengths),
        'min_length': min(lengths),
        'max_length': max(lengths),
        'most_common_length': most_common_len,
        'n_sequences_with_most_common_length': most_common_n,
        'n_unique_lengths': len(length_counts),
    }
    print(f"  {os.path.basename(fasta_file)}: "
          f"dominant length = {most_common_len} nt ({most_common_n}/{len(lengths)} sequences), "
          f"range = [{report['min_length']}, {report['max_length']}]")
    if report['n_unique_lengths'] > 1:
        print(f"      Note: {report['n_unique_lengths']} distinct lengths present in this file.")
    return report


# ============================================================================
# Section 2: Model architecture
# ============================================================================

class VAE_Dirichlet(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim, dropout_rate=DROPOUT_RATE):
        super(VAE_Dirichlet, self).__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.latent_dim = latent_dim
        self.dropout_rate = dropout_rate

        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.LayerNorm(hidden_dim),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, latent_dim)
        )
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.ReLU(),
            nn.LayerNorm(hidden_dim),
            nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, input_dim),
            nn.Sigmoid()
        )

    def encode(self, x):
        alpha = self.encoder(x)
        alpha = torch.clamp(alpha, min=1e-6, max=1e6)
        alpha = torch.nn.functional.softmax(alpha, dim=-1)
        return alpha

    def reparameterize(self, alpha):
        alpha = torch.clamp(alpha, min=1e-6)
        gamma = torch.distributions.Gamma(alpha, torch.ones_like(alpha)).sample()
        z = gamma / (gamma.sum(-1, keepdim=True) + 1e-8)
        return z

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        alpha = self.encode(x)
        z = self.reparameterize(alpha)
        return self.decode(z), alpha, z


def dirichlet_loss_split(recon_x, x, alpha, prior_alpha=0.1):
    recon_loss = nn.functional.mse_loss(recon_x, x, reduction='sum')

    def kl_divergence_dirichlet(alpha, prior_alpha):
        prior_alpha_tensor = torch.tensor(prior_alpha, dtype=alpha.dtype, device=alpha.device)
        term1 = torch.lgamma(alpha.sum(-1)) - torch.lgamma(prior_alpha_tensor * alpha.shape[-1])
        term2 = torch.sum(torch.lgamma(prior_alpha_tensor) - torch.lgamma(alpha), dim=-1)
        term3 = torch.sum(
            (alpha - prior_alpha_tensor) * (torch.digamma(alpha) - torch.digamma(alpha.sum(-1, keepdim=True))),
            dim=-1
        )
        return term1 + term2 + term3

    kl_loss = kl_divergence_dirichlet(alpha, prior_alpha).sum()
    total_loss = recon_loss + kl_loss
    return total_loss, recon_loss, kl_loss


# ============================================================================
# Section 3: Biological post-processing utilities
# ============================================================================

def dinucleotide_shuffle(seq, num_shuffles=10):
    if len(seq) < 2:
        return seq
    seq = seq.upper().replace('T', 'U')
    seq = ''.join([c for c in seq if c in 'ACGU'])
    if len(seq) < 2:
        return ''.join(random.choices('ACGU', k=len(seq)))

    di_nuc_counts = Counter()
    for i in range(len(seq) - 1):
        di_nuc_counts[seq[i:i + 2]] += 1

    graph = defaultdict(list)
    for dn, count in di_nuc_counts.items():
        for _ in range(count):
            graph[dn[0]].append(dn[1])

    start_char = seq[0]
    result = [start_char]
    current = start_char
    edges_used = 0
    total_edges = sum(len(v) for v in graph.values())

    while edges_used < total_edges and current in graph and graph[current]:
        next_char = graph[current].pop()
        result.append(next_char)
        current = next_char
        edges_used += 1

    if len(result) < len(seq):
        result = list(seq)
        random.shuffle(result)

    return ''.join(result[:len(seq)])


def generate_dinucleotide_shuffled_background(sequences, num_shuffles=5):
    background = []
    for seq in sequences:
        seq_str = str(seq).upper().replace('T', 'U')
        seq_str = ''.join([c for c in seq_str if c in 'ACGU'])
        if len(seq_str) < 6:
            continue
        for _ in range(num_shuffles):
            shuffled = dinucleotide_shuffle(seq_str, num_shuffles=20)
            background.append(shuffled)
    return background


def calculate_enrichment_pvalue_and_qvalue(candidate_kmers, peak_seqs, background_seqs):
    pvals, kmers_list = [], []
    for kmer in candidate_kmers:
        a = sum(1 for seq in peak_seqs if kmer in seq)
        b = len(peak_seqs) - a
        c = sum(1 for seq in background_seqs if kmer in seq)
        d = len(background_seqs) - c
        if a + b == 0 or c + d == 0 or a + c == 0 or b + d == 0:
            p_val = 1.0
        else:
            try:
                _, p_val = fisher_exact([[a, b], [c, d]], alternative='greater')
            except Exception:
                p_val = 1.0
        pvals.append(p_val)
        kmers_list.append(kmer)

    pvals = np.array(pvals)
    _, qvals = fdrcorrection(pvals, alpha=0.05, method='indep')
    if qvals is None:
        qvals = pvals.copy()

    return {kmer: {'pval': float(pvals[i]), 'qval': float(qvals[i])} for i, kmer in enumerate(kmers_list)}


def precompute_accessibility_profiles(sequences, seq_ids=None, real_icshape=None,
                                       max_null_fraction_allowed=MAX_ICSHAPE_NULL_FRACTION):
    if seq_ids is None:
        seq_ids = [None] * len(sequences)
    if real_icshape is None:
        real_icshape = {}

    profiles = []
    n_real, n_computed, n_failed = 0, 0, 0

    for seq, sid in zip(sequences, seq_ids):
        clean_seq = ''.join(c for c in seq.upper().replace('T', 'U') if c in 'ACGU')
        if not clean_seq:
            profiles.append(np.array([]))
            n_failed += 1
            continue

        used_real = False
        if sid is not None and sid in real_icshape:
            raw_scores = real_icshape[sid]
            if raw_scores is not None and len(raw_scores) == len(clean_seq):
                null_frac = sum(1 for v in raw_scores if v is None) / len(raw_scores)
                if null_frac <= max_null_fraction_allowed:
                    profile = np.array([np.nan if v is None else float(v) for v in raw_scores])
                    profiles.append(profile)
                    n_real += 1
                    used_real = True

        if not used_real:
            try:
                fc = RNA.fold_compound(clean_seq)
                fc.pf()
                n = len(clean_seq)
                bpp = fc.bpp()
                unpaired = np.ones(n, dtype=np.float64)
                for i in range(1, n + 1):
                    total_pair_prob = 0.0
                    for j in range(1, n + 1):
                        if i != j and bpp[i][j] > 0:
                            total_pair_prob += bpp[i][j]
                    unpaired[i - 1] = max(0.0, 1.0 - total_pair_prob)
                unpaired = np.clip(unpaired, 0.0, 1.0)
                profiles.append(unpaired)
                n_computed += 1
            except Exception as e:
                print(f"  Warning: ViennaRNA folding failed (len={len(clean_seq)}): {str(e)[:100]}")
                profiles.append(np.full(len(clean_seq), np.nan))
                n_failed += 1

    total = len(sequences)
    if n_real > 0 and n_computed == 0:
        source_label = "real_icshape_experimental"
    elif n_real > 0 and n_computed > 0:
        source_label = "mixed_real_icshape_and_computational_fold"
    else:
        source_label = "ViennaRNA_computational_fold"

    summary = {
        'n_real_icshape_used': n_real,
        'n_computational_fold_used': n_computed,
        'n_failed': n_failed,
        'total': total,
        'accessibility_source': source_label,
    }
    print(f"    Accessibility source: {n_real}/{total} real icSHAPE scores, "
          f"{n_computed}/{total} ViennaRNA computational folds, {n_failed} failed.")
    return profiles, summary


def calculate_accessibility_score_optimized(kmer, peak_seqs, accessibility_profiles):
    total_accessibility, count = 0.0, 0
    clean_kmer = kmer.upper().replace('T', 'U')
    clean_kmer = ''.join([c for c in clean_kmer if c in 'ACGU'])
    if len(clean_kmer) != len(kmer):
        return 0.0

    for orig_seq, profile in zip(peak_seqs, accessibility_profiles):
        if len(profile) == 0:
            continue
        clean_seq = orig_seq.upper().replace('T', 'U')
        clean_seq = ''.join([c for c in clean_seq if c in 'ACGU'])

        if clean_kmer not in clean_seq:
            continue

        start = 0
        while True:
            pos = clean_seq.find(clean_kmer, start)
            if pos == -1:
                break
            kmer_end = pos + len(clean_kmer)
            if kmer_end <= len(profile):
                window_vals = profile[pos:kmer_end]
            else:
                window_vals = profile[pos:]
            if len(window_vals) > 0:
                valid_vals = window_vals[~np.isnan(window_vals)]
                if len(valid_vals) > 0:
                    total_accessibility += float(np.mean(valid_vals))
                    count += 1
            start = pos + 1

    return total_accessibility / count if count > 0 else 0.0


def calculate_centrality_score(kmer, peak_seqs):
    total_norm_dist, count = 0.0, 0
    for seq in peak_seqs:
        if kmer not in seq:
            continue
        peak_center = len(seq) / 2.0
        start = 0
        while True:
            pos = seq.find(kmer, start)
            if pos == -1:
                break
            kmer_center = pos + len(kmer) / 2.0
            distance = abs(kmer_center - peak_center)
            normalized_dist = 1.0 - (distance / (len(seq) / 2.0 + 1e-8))
            total_norm_dist += max(0.0, min(1.0, normalized_dist))
            count += 1
            start = pos + 1
    return total_norm_dist / count if count > 0 else 0.0


def normalize_enrichment_score(p_val):
    log_score = -np.log10(p_val + 1e-10)
    return 1 / (1 + np.exp(-(log_score - 2)))


def rbp_specific_postprocessing(candidate_kmers, peak_seqs, peak_ids=None,
                                 real_icshape=None, real_negative_seqs=None,
                                 min_real_negatives=MIN_REAL_NEGATIVES_FOR_BACKGROUND):
    if real_negative_seqs is not None and len(real_negative_seqs) >= min_real_negatives:
        background_seqs = real_negative_seqs
        background_source = "real_non_enriched_clip_background (experimentally derived negative set)"
        print(f"    Background: using {len(background_seqs)} real negative sequences.")
    else:
        background_seqs = generate_dinucleotide_shuffled_background(peak_seqs, num_shuffles=5)
        if len(background_seqs) == 0:
            background_seqs = peak_seqs
        background_source = "dinucleotide_shuffle"
        n_avail = len(real_negative_seqs) if real_negative_seqs is not None else 0
        print(f"    Background: available real negatives ({n_avail}) insufficient "
              f"(minimum required={min_real_negatives}); using dinucleotide shuffle instead.")

    enrichment_results = calculate_enrichment_pvalue_and_qvalue(candidate_kmers, peak_seqs, background_seqs)
    accessibility_profiles, acc_summary = precompute_accessibility_profiles(
        peak_seqs, seq_ids=peak_ids, real_icshape=real_icshape
    )

    accessibility_scores, centrality_scores = {}, {}
    for kmer in candidate_kmers:
        accessibility_scores[kmer] = calculate_accessibility_score_optimized(
            kmer, peak_seqs, accessibility_profiles
        )
        centrality_scores[kmer] = calculate_centrality_score(kmer, peak_seqs)

    rbp_scores = {}
    for kmer in candidate_kmers:
        pval = enrichment_results[kmer]['pval']
        qval = enrichment_results[kmer]['qval']
        enrichment_norm = normalize_enrichment_score(pval)
        final_score = (0.5 * enrichment_norm) + (0.3 * accessibility_scores[kmer]) + (0.2 * centrality_scores[kmer])
        rbp_scores[kmer] = {
            'rbp_final_score': final_score,
            'enrichment_pval': pval,
            'enrichment_qval': qval,
            'enrichment_norm': enrichment_norm,
            'accessibility': accessibility_scores[kmer],
            'centrality': centrality_scores[kmer]
        }

    metadata = {
        'background_source': background_source,
        'n_background_sequences': len(background_seqs),
        'n_real_negatives_available': len(real_negative_seqs) if real_negative_seqs is not None else 0,
        'min_real_negatives_required': min_real_negatives,
        **acc_summary,
    }
    return rbp_scores, metadata


# ============================================================================
# Section 4: Biologically grounded PWM construction
# ============================================================================

def _hamming_distance(a, b):
    return sum(1 for x, y in zip(a, b) if x != y)


def build_pwm_from_motif_occurrences(motif, peak_seqs,
                                      max_mismatches=PWM_MAX_MISMATCHES,
                                      pseudocount_scale=PWM_PSEUDOCOUNT_SCALE,
                                      min_pseudocount=PWM_MIN_PSEUDOCOUNT,
                                      center_window_fraction=PWM_CENTER_WINDOW_FRACTION,
                                      min_info_content=PWM_MIN_INFO_CONTENT):
    """
    Builds a biologically grounded position weight matrix (PWM) for a motif,
    with three key design choices:

      (1) Non-overlapping occurrences, selected greedily by minimum Hamming
          distance first (rather than counting every overlapping sliding
          window separately).
      (2) A relative pseudocount that scales with sqrt(occurrence_count),
          instead of a fixed value that over-smooths PWMs built from a
          small number of sites.
      (3) A centrality filter: only occurrences near the center of each
          peak sequence are counted, reducing noise from sites far from
          the true binding location.

    Returns (pwm, occurrence_count, mean_information_content_bits), or
    None if no valid occurrence is found (or if min_info_content is set
    and the resulting PWM does not meet the quality threshold).
    """
    motif = motif.upper().replace('T', 'U')
    motif = ''.join(c for c in motif if c in NUC_TO_IDX)
    motif_len = len(motif)
    if motif_len == 0:
        return None

    position_counts = np.zeros((motif_len, 4))
    occurrence_count = 0

    for seq in peak_seqs:
        clean_seq = seq.upper().replace('T', 'U')
        clean_seq = ''.join(c for c in clean_seq if c in NUC_TO_IDX)
        L = len(clean_seq)
        if L < motif_len:
            continue

        # Restrict to the central region of the sequence to reduce edge noise
        margin = int(L * (1 - center_window_fraction) / 2)
        lo, hi = margin, L - margin - motif_len + 1
        if hi <= lo:
            lo, hi = 0, L - motif_len + 1

        # Collect all candidate windows within the allowed Hamming distance
        candidates = []
        for start in range(lo, hi):
            window = clean_seq[start:start + motif_len]
            d = _hamming_distance(window, motif)
            if d <= max_mismatches:
                candidates.append((d, start, window))

        # Greedy selection: best (lowest-mismatch) hits first, then non-overlapping
        candidates.sort(key=lambda x: x[0])
        used_positions = set()
        for d, start, window in candidates:
            span = range(start, start + motif_len)
            if any(p in used_positions for p in span):
                continue
            used_positions.update(span)
            for i, nuc in enumerate(window):
                position_counts[i, NUC_TO_IDX[nuc]] += 1
            occurrence_count += 1

    if occurrence_count == 0:
        return None

    # Relative pseudocount, scaled by occurrence count
    effective_pseudocount = max(min_pseudocount,
                                 pseudocount_scale * np.sqrt(occurrence_count) / 10.0)
    pfm_with_pseudocount = position_counts + effective_pseudocount
    pwm = pfm_with_pseudocount / pfm_with_pseudocount.sum(axis=1, keepdims=True)

    # Information content (used for reporting and optional filtering)
    bg = 0.25
    ic_per_col = np.sum(pwm * np.log2((pwm + 1e-9) / bg), axis=1)
    mean_ic = float(np.mean(ic_per_col))

    if min_info_content is not None and mean_ic < min_info_content:
        return None  # motif does not meet the minimum PWM quality threshold

    return pwm, occurrence_count, mean_ic


def compute_background_frequencies(peak_seqs):
    """Computes empirical nucleotide frequencies from the training sequences,
    used both in the MEME output header and as the Tomtom -bfile input."""
    counts = Counter()
    for seq in peak_seqs:
        clean = seq.upper().replace('T', 'U')
        for c in clean:
            if c in NUC_TO_IDX:
                counts[c] += 1
    total = sum(counts.values())
    if total == 0:
        return {'A': 0.25, 'C': 0.25, 'G': 0.25, 'U': 0.25}
    return {nuc: counts.get(nuc, 0) / total for nuc in 'ACGU'}


def export_pwms_to_meme_format(motif_pwm_dict, output_path, protein_name, background_freqs=None):
    if background_freqs is None:
        background_freqs = {'A': 0.25, 'C': 0.25, 'G': 0.25, 'U': 0.25}
    with open(output_path, 'w') as f:
        f.write("MEME version 4\n\n")
        f.write("ALPHABET= ACGU\n\n")
        f.write("strands: + -\n\n")
        f.write("Background letter frequencies\n")
        f.write(f"A {background_freqs['A']:.6f} C {background_freqs['C']:.6f} "
                f"G {background_freqs['G']:.6f} U {background_freqs['U']:.6f}\n\n")
        for motif, (pwm, n_sites, mean_ic) in motif_pwm_dict.items():
            safe_name = f"{protein_name}_{motif}"
            f.write(f"MOTIF {safe_name}\n")
            f.write(f"letter-probability matrix: alength= 4 w= {pwm.shape[0]} nsites= {n_sites} E= 0\n")
            for row in pwm:
                f.write(" ".join(f"{v:.6f}" for v in row) + "\n")
            f.write("\n")


def build_and_export_all_motif_pwms(rbp_scores, peak_seqs, save_path, protein_name,
                                     max_mismatches=PWM_MAX_MISMATCHES,
                                     pseudocount_scale=PWM_PSEUDOCOUNT_SCALE,
                                     min_pseudocount=PWM_MIN_PSEUDOCOUNT,
                                     center_window_fraction=PWM_CENTER_WINDOW_FRACTION,
                                     min_info_content=PWM_MIN_INFO_CONTENT):
    """
    Builds a PWM for every candidate motif in rbp_scores, using
    non-overlapping occurrences, a relative pseudocount, and the
    centrality filter implemented in build_pwm_from_motif_occurrences.
    """
    all_motifs = sorted(rbp_scores.items(), key=lambda x: x[1]['rbp_final_score'], reverse=True)
    print(f"  Building PWMs (non-overlapping occurrences, relative pseudocount, "
          f"centrality filter; max_mismatches={max_mismatches}) for "
          f"all {len(all_motifs)} candidate motifs ...")

    background_freqs = compute_background_frequencies(peak_seqs)
    print(f"  Empirical nucleotide frequencies: "
          f"A={background_freqs['A']:.3f} C={background_freqs['C']:.3f} "
          f"G={background_freqs['G']:.3f} U={background_freqs['U']:.3f}")

    motif_pwm_dict = {}
    pwm_summary_rows = []
    n_failed = 0

    for kmer, scores in all_motifs:
        result = build_pwm_from_motif_occurrences(
            kmer, peak_seqs,
            max_mismatches=max_mismatches,
            pseudocount_scale=pseudocount_scale,
            min_pseudocount=min_pseudocount,
            center_window_fraction=center_window_fraction,
            min_info_content=min_info_content,
        )
        if result is None:
            n_failed += 1
            continue
        pwm, n_sites, mean_ic = result
        motif_pwm_dict[kmer] = (pwm, n_sites, mean_ic)
        pwm_summary_rows.append({
            'motif': kmer,
            'n_occurrences_used_for_pwm': n_sites,
            'mean_information_content_bits': mean_ic,
            'max_mismatches_allowed': max_mismatches,
            'center_window_fraction': center_window_fraction,
            'rbp_final_score': scores['rbp_final_score'],
            'enrichment_pval': scores['enrichment_pval'],
            'enrichment_qval': scores['enrichment_qval'],
            'accessibility': scores['accessibility'],
            'centrality': scores['centrality'],
        })

    meme_path = os.path.join(save_path, f'{protein_name}_ALL_motifs.meme')
    export_pwms_to_meme_format(motif_pwm_dict, meme_path, protein_name, background_freqs=background_freqs)

    # Background frequencies are also saved separately (for Tomtom's -bfile)
    bg_path = os.path.join(save_path, f'{protein_name}_background.txt')
    with open(bg_path, 'w') as f:
        for nuc in 'ACGU':
            f.write(f"{nuc}\t{background_freqs[nuc]:.6f}\n")

    summary_csv_path = os.path.join(save_path, f'{protein_name}_ALL_pwm_summary.csv')
    pd.DataFrame(pwm_summary_rows).to_csv(summary_csv_path, index=False)

    print(f"  PWMs successfully built for {len(motif_pwm_dict)}/{len(all_motifs)} motifs "
          f"({n_failed} rejected: zero occurrences or below quality threshold).")
    print(f"  Full MEME file: {meme_path}")
    print(f"  Background file (for Tomtom -bfile): {bg_path}")
    print(f"  PWM summary (CSV): {summary_csv_path}")
    return motif_pwm_dict, meme_path, bg_path


# ============================================================================
# Tomtom motif comparison
# ============================================================================

def run_tomtom_comparison(protein_meme_file, attract_meme_file, output_dir, protein_name,
                           background_file=None, motif_len_for_overlap=6,
                           qval_threshold=0.05):
    """
    Runs Tomtom to compare discovered motifs against a reference motif
    database (e.g., ATtRACT).

    Notes on the flags used:
      - Small-sample correction (ssc) is left enabled, the recommended
        MEME Suite default for PWMs built from a limited number of sites.
      - "-bfile" is used when a background_file is provided, so Tomtom
        scores matches against the empirical nucleotide frequencies
        computed from the training sequences (rather than assuming a
        uniform background).
      - "-min-overlap" is set to max(motif_len - 1, 4), requiring an
        almost-complete alignment rather than a short, noisy partial
        match.
    """
    if shutil.which("tomtom") is None:
        print("  Warning: 'tomtom' not found on PATH. Install the MEME Suite:")
        print("     conda install -c bioconda meme")
        return None

    if not os.path.exists(attract_meme_file):
        print(f"  Warning: ATtRACT MEME file not found: {attract_meme_file}")
        return None

    min_overlap = max(motif_len_for_overlap - 1, 4)

    tomtom_out_dir = os.path.join(output_dir, f'{protein_name}_tomtom_out')
    cmd = ["tomtom", "-oc", tomtom_out_dir,
           "-min-overlap", str(min_overlap),
           "-dist", "pearson",
           "-evalue", "-thresh", str(TOMTOM_EVALUE_THRESH)]

    if background_file is not None and os.path.exists(background_file):
        cmd += ["-bfile", background_file]
        print(f"  Using empirical background frequencies: {background_file}")
    else:
        print("  No background file provided; Tomtom will use its default uniform assumption.")

    cmd += [protein_meme_file, attract_meme_file]

    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True, timeout=1200)
    except subprocess.CalledProcessError as e:
        print(f"  Error: Tomtom failed: {str(e.stderr)[:300]}")
        return None
    except subprocess.TimeoutExpired:
        print("  Error: Tomtom timed out.")
        return None

    tomtom_tsv = os.path.join(tomtom_out_dir, "tomtom.tsv")
    if not os.path.exists(tomtom_tsv):
        print("  Error: tomtom.tsv output file not found.")
        return None

    try:
        tomtom_df = pd.read_csv(tomtom_tsv, sep='\t', comment='#')
        tomtom_df.columns = [c.strip() for c in tomtom_df.columns]
        tomtom_df = tomtom_df.dropna(subset=['Query_ID']) if 'Query_ID' in tomtom_df.columns else tomtom_df
    except Exception as e:
        print(f"  Error reading tomtom.tsv: {e}")
        return None

    qcol = 'q-value' if 'q-value' in tomtom_df.columns else [c for c in tomtom_df.columns if 'q' in c.lower()][0]
    qcol_id = 'Query_ID' if 'Query_ID' in tomtom_df.columns else tomtom_df.columns[0]

    significant = tomtom_df[tomtom_df[qcol] < qval_threshold] if not tomtom_df.empty else tomtom_df

    query_motifs_all = set()
    with open(protein_meme_file) as f:
        for line in f:
            if line.startswith("MOTIF"):
                query_motifs_all.add(line.split()[1])

    matched_motifs = set(significant[qcol_id].unique()) if not significant.empty else set()
    agreement_pct = 100.0 * len(matched_motifs) / len(query_motifs_all) if query_motifs_all else 0.0

    tomtom_df.to_csv(os.path.join(output_dir, f'{protein_name}_tomtom_full_results.csv'), index=False)

    summary = {
        'protein': protein_name,
        'n_query_motifs': len(query_motifs_all),
        'n_significant_matches_qlt0.05': len(matched_motifs),
        'tomtom_agreement_pct': agreement_pct,
        'min_overlap_used': min_overlap,
        'background_file_used': background_file if background_file else 'uniform_default',
    }
    pd.DataFrame([summary]).to_csv(
        os.path.join(output_dir, f'{protein_name}_tomtom_agreement_summary.csv'), index=False
    )
    print(f"  Tomtom: {len(matched_motifs)}/{len(query_motifs_all)} motifs "
          f"({agreement_pct:.1f}%) had a significant match (q<{qval_threshold}) to the reference database.")
    return summary


# ============================================================================
# Section 5: VAE evaluation metrics
# ============================================================================

ACTIVE_UNIT_VARIANCE_THRESHOLD = 0.01
SPARSITY_NEAR_ZERO_THRESHOLD = 0.01


def extract_all_z_values(vae_model, dataloader):
    vae_model.eval()
    all_z = []
    with torch.no_grad():
        for batch in dataloader:
            batch = batch.to(DEVICE)
            alpha = vae_model.encode(batch)
            z = vae_model.reparameterize(alpha)
            all_z.append(z.cpu().numpy())
    return np.vstack(all_z)


def calculate_vae_metrics(all_z_values, vae_model, dataloader, recon_percentile=25):
    metrics = {}
    recon_errors = []
    vae_model.eval()
    with torch.no_grad():
        for batch in dataloader:
            batch = batch.to(DEVICE)
            recon_batch, _, _ = vae_model(batch)
            errors = torch.mean((recon_batch - batch) ** 2, dim=1)
            recon_errors.extend(errors.cpu().numpy())

    recon_errors = np.array(recon_errors)
    metrics['reconstruction_error_mean'] = float(np.mean(recon_errors))
    metrics['reconstruction_error_std'] = float(np.std(recon_errors))

    threshold = np.percentile(recon_errors, recon_percentile)
    metrics['reconstruction_accuracy'] = float(np.mean(recon_errors < threshold))
    metrics['recon_threshold_used'] = float(threshold)

    z_var = np.var(all_z_values, axis=0)
    active_units = int(np.sum(z_var > ACTIVE_UNIT_VARIANCE_THRESHOLD))
    metrics['active_units'] = active_units
    metrics['active_units_ratio'] = active_units / all_z_values.shape[1]
    metrics['active_units_variance_threshold'] = ACTIVE_UNIT_VARIANCE_THRESHOLD

    if len(all_z_values) > 10 and all_z_values.shape[1] > 1:
        try:
            n_clusters = min(10, all_z_values.shape[0] // 10 + 1)
            kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
            labels = kmeans.fit_predict(all_z_values)
            metrics['silhouette_score'] = float(silhouette_score(all_z_values, labels))
        except Exception:
            metrics['silhouette_score'] = 0.0
    else:
        metrics['silhouette_score'] = 0.0

    metrics['sparsity'] = float(np.mean(all_z_values < SPARSITY_NEAR_ZERO_THRESHOLD))
    metrics['sparsity_near_zero_threshold'] = SPARSITY_NEAR_ZERO_THRESHOLD

    return metrics


# ============================================================================
# Section 6: Training with a real train/test holdout split
# ============================================================================

def train_vae_with_real_holdout(X_train, X_test, input_dim, hidden_dim, latent_dim,
                                  epochs=100, batch_size=128, lr=1e-3, weight_decay=1e-5,
                                  prior_alpha=0.1, dropout_rate=DROPOUT_RATE, verbose=True):
    model = VAE_Dirichlet(input_dim, hidden_dim, latent_dim, dropout_rate=dropout_rate).to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)

    train_loader = DataLoader(RNADataset(X_train), batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(RNADataset(X_test), batch_size=batch_size, shuffle=False)

    history = {'train_recon': [], 'train_kl': [], 'test_recon': [], 'test_kl': []}

    for epoch in range(epochs):
        model.train()
        epoch_recon, epoch_kl = 0.0, 0.0
        for batch in train_loader:
            batch = batch.to(DEVICE)
            optimizer.zero_grad()
            recon_batch, alpha, z = model(batch)
            loss, recon_l, kl_l = dirichlet_loss_split(recon_batch, batch, alpha, prior_alpha)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
            optimizer.step()
            epoch_recon += recon_l.item()
            epoch_kl += kl_l.item()

        history['train_recon'].append(epoch_recon / len(train_loader.dataset))
        history['train_kl'].append(epoch_kl / len(train_loader.dataset))

        model.eval()
        test_recon, test_kl = 0.0, 0.0
        with torch.no_grad():
            for batch in test_loader:
                batch = batch.to(DEVICE)
                recon_batch, alpha, z = model(batch)
                _, recon_l, kl_l = dirichlet_loss_split(recon_batch, batch, alpha, prior_alpha)
                test_recon += recon_l.item()
                test_kl += kl_l.item()
        history['test_recon'].append(test_recon / len(test_loader.dataset))
        history['test_kl'].append(test_kl / len(test_loader.dataset))

        if verbose and ((epoch + 1) % 10 == 0 or epoch == 0):
            print(f"    Epoch {epoch+1:3d}/{epochs} | "
                  f"Train Recon={history['train_recon'][-1]:.4f} KL={history['train_kl'][-1]:.4f} | "
                  f"Test Recon={history['test_recon'][-1]:.4f} KL={history['test_kl'][-1]:.4f}")

    return model, history, train_loader, test_loader


def plot_loss_curves(history, save_path, protein_name):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].plot(history['train_recon'], label='Train', linewidth=2)
    axes[0].plot(history['test_recon'], label='Test (held-out)', linewidth=2, linestyle='--')
    axes[0].set_title(f'{protein_name} — Reconstruction Loss', fontweight='bold')
    axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('MSE Sum Loss')
    axes[0].legend(); axes[0].grid(alpha=0.3)

    axes[1].plot(history['train_kl'], label='Train', linewidth=2, color='darkorange')
    axes[1].plot(history['test_kl'], label='Test (held-out)', linewidth=2, linestyle='--', color='red')
    axes[1].set_title(f'{protein_name} — KL Divergence', fontweight='bold')
    axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('KL Loss')
    axes[1].legend(); axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(save_path, f'{protein_name}_loss_curves.jpg'), dpi=300, bbox_inches='tight')
    plt.close()


def plot_diagnostic_figures(all_z_train, X_train, model, train_loader, save_path, protein_name):
    plt.figure(figsize=(14, 10))
    num_samples = min(2000, all_z_train.shape[0])
    sns.heatmap(all_z_train[:num_samples], cmap='viridis', cbar_kws={'label': 'Activation Value'})
    plt.title(f'{protein_name} — Latent Representations Heatmap', fontweight='bold')
    plt.xlabel('Latent Dimensions (Z)'); plt.ylabel('Samples')
    plt.savefig(os.path.join(save_path, f'{protein_name}_latent_heatmap.jpg'), dpi=300, bbox_inches='tight')
    plt.close()

    plt.figure(figsize=(12, 6))
    for i in range(min(8, all_z_train.shape[1])):
        plt.hist(all_z_train[:, i], bins=50, alpha=0.6, label=f'Z{i+1}')
    plt.title(f'{protein_name} — Distribution of Top 8 Latent Dimensions', fontweight='bold')
    plt.xlabel('Activation Value'); plt.ylabel('Frequency')
    plt.legend(); plt.grid(alpha=0.3)
    plt.savefig(os.path.join(save_path, f'{protein_name}_latent_distribution.jpg'), dpi=300, bbox_inches='tight')
    plt.close()

    recon_errors = []
    model.eval()
    with torch.no_grad():
        for batch in train_loader:
            batch = batch.to(DEVICE)
            recon_batch, _, _ = model(batch)
            errors = torch.mean((recon_batch - batch) ** 2, dim=1).cpu().numpy()
            recon_errors.extend(errors)
    recon_errors = np.array(recon_errors)

    plt.figure(figsize=(10, 6))
    plt.hist(recon_errors, bins=60, color='steelblue', edgecolor='black')
    plt.axvline(np.percentile(recon_errors, 25), color='red', linestyle='--', label='25th Percentile')
    plt.title(f'{protein_name} — Reconstruction Error Distribution (Train)', fontweight='bold')
    plt.xlabel('MSE Error'); plt.ylabel('Frequency')
    plt.legend(); plt.grid(alpha=0.3)
    plt.savefig(os.path.join(save_path, f'{protein_name}_reconstruction_error_dist.jpg'), dpi=300, bbox_inches='tight')
    plt.close()


# ============================================================================
# Section 7: Sensitivity analysis over latent_dim
# ============================================================================

def run_latent_dim_sensitivity(X_train, X_test, input_dim, hidden_dim, save_path, protein_name,
                                 latent_dims_to_test=(10, 20, 30, 50, 100),
                                 epochs=60, batch_size=128):
    print(f"  --- Latent-dimension sensitivity analysis for {protein_name} ---")
    results = []
    for ld in latent_dims_to_test:
        print(f"    Training with latent_dim = {ld} ...")
        model, history, train_loader, test_loader = train_vae_with_real_holdout(
            X_train, X_test, input_dim, hidden_dim, ld,
            epochs=epochs, batch_size=batch_size, verbose=False
        )
        all_z_train = extract_all_z_values(model, train_loader)
        metrics = calculate_vae_metrics(all_z_train, model, train_loader)

        results.append({
            'protein': protein_name,
            'latent_dim': ld,
            'final_train_recon': history['train_recon'][-1],
            'final_test_recon': history['test_recon'][-1],
            'active_units': metrics['active_units'],
            'active_units_ratio': metrics['active_units_ratio'],
            'sparsity': metrics['sparsity'],
            'silhouette_score': metrics['silhouette_score']
        })

    df = pd.DataFrame(results)
    df.to_csv(os.path.join(save_path, f'{protein_name}_latent_dim_sensitivity.csv'), index=False)

    fig, axes = plt.subplots(1, 4, figsize=(22, 5))
    axes[0].plot(df['latent_dim'], df['final_train_recon'], marker='o', label='Train')
    axes[0].plot(df['latent_dim'], df['final_test_recon'], marker='s', label='Test')
    axes[0].set_title('Reconstruction Loss vs Latent Dim'); axes[0].set_xlabel('Latent Dim'); axes[0].legend()

    axes[1].plot(df['latent_dim'], df['active_units_ratio'], marker='o', color='green')
    axes[1].set_title('Active Units Ratio vs Latent Dim'); axes[1].set_xlabel('Latent Dim')

    axes[2].plot(df['latent_dim'], df['sparsity'], marker='o', color='orange')
    axes[2].set_title('Sparsity vs Latent Dim'); axes[2].set_xlabel('Latent Dim')

    axes[3].plot(df['latent_dim'], df['silhouette_score'], marker='o', color='purple')
    axes[3].set_title('Silhouette Score vs Latent Dim'); axes[3].set_xlabel('Latent Dim')

    for ax in axes:
        ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(save_path, f'{protein_name}_latent_dim_sensitivity.jpg'), dpi=300, bbox_inches='tight')
    plt.close()

    print(f"  Sensitivity analysis results for {protein_name} saved.")
    return df


# ============================================================================
# Section 7.5: Multi-k robustness analysis (Table 5)
# ============================================================================

def run_multi_k_robustness_analysis(train_sequences, test_sequences, save_path, protein_name,
                                      k_values=(4, 5, 6, 7), reference_k=6,
                                      hidden_dim=200, latent_dim=30, epochs=100, top_n=30):
    print(f"  --- Multi-k robustness analysis for {protein_name} (k={k_values}) ---")
    results_per_k = {}
    for k in k_values:
        print(f"    Training independent model with k={k} ...")
        Xtr, kdict = extract_rna_kmer_features_with_shared_dict(train_sequences, k=k)
        Xte, _ = extract_rna_kmer_features_with_shared_dict(test_sequences, k=k, kmer_dict=kdict)
        model, history, train_loader, _ = train_vae_with_real_holdout(
            Xtr, Xte, Xtr.shape[1], hidden_dim, latent_dim, epochs=epochs, verbose=False
        )
        all_z = extract_all_z_values(model, train_loader)
        top_kmers = get_top_kmers_per_z(all_z, Xtr, kdict, train_sequences, k=k, top_n=top_n)
        merged_kmers = set()
        for z_dim, data in top_kmers.items():
            for kmer, count in data['kmers']:
                merged_kmers.add(kmer)
        results_per_k[k] = merged_kmers
        print(f"      -> {len(merged_kmers)} unique candidate motifs for k={k}")

    reference_set = results_per_k[reference_k]
    rows = []
    for k in k_values:
        if k == reference_k:
            continue
        other_set = results_per_k[k]
        n_contained = 0
        for ref_motif in reference_set:
            match_found = False
            for other_motif in other_set:
                if (ref_motif in other_motif) or (other_motif in ref_motif):
                    match_found = True
                    break
            if match_found:
                n_contained += 1
        agreement_pct = 100.0 * n_contained / len(reference_set) if reference_set else 0.0
        rows.append({
            'protein': protein_name,
            'k_reference': reference_k,
            'k_compared': k,
            'n_reference_motifs': len(reference_set),
            'n_compared_motifs': len(other_set),
            'n_containment_matches': n_contained,
            'agreement_pct_vs_reference_k': round(agreement_pct, 2)
        })

    df = pd.DataFrame(rows)
    table5_path = os.path.join(save_path, f'{protein_name}_table5_multi_k_robustness.csv')
    df.to_csv(table5_path, index=False)
    print(f"  Table 5 (multi-k robustness) for {protein_name} saved to {table5_path}")
    return df, results_per_k


# ============================================================================
# Section 8: Candidate motif extraction from the latent space + activity heatmap
# ============================================================================

def get_top_kmers_per_z(all_z_values, kmer_features, kmer_dict, sequences, k, top_n=30):
    num_z_dims = all_z_values.shape[1]
    top_kmers = {}
    idx_to_kmer = {v: kk for kk, v in kmer_dict.items()}

    for z_dim in range(num_z_dims):
        z_scores = all_z_values[:, z_dim]
        top_indices = np.argsort(z_scores)[-top_n:]
        kmer_counter = Counter()
        for idx in top_indices:
            kmer_counts_row = kmer_features[idx]
            for kmer_idx in np.where(kmer_counts_row > 0)[0]:
                kmer = idx_to_kmer[kmer_idx]
                if len(kmer) == k:
                    kmer_counter[kmer] += int(kmer_counts_row[kmer_idx])
        top_kmers[z_dim] = {
            'kmers': [(kmer, count) for kmer, count in kmer_counter.most_common(top_n)],
            'sequences': [sequences[idx] for idx in top_indices]
        }
    return top_kmers


def plot_motif_activity_heatmap(top_kmers, top_motifs_list, save_path, protein_name):
    num_z_dims = len(top_kmers)
    num_motifs = len(top_motifs_list)
    activity_matrix = np.zeros((num_z_dims, num_motifs))

    for z_dim in range(num_z_dims):
        kmers_in_z = {kmer: count for kmer, count in top_kmers[z_dim]['kmers']}
        for j, motif in enumerate(top_motifs_list):
            activity_matrix[z_dim, j] = kmers_in_z.get(motif, 0)

    row_max = activity_matrix.max(axis=1, keepdims=True)
    row_max[row_max == 0] = 1
    activity_matrix_norm = activity_matrix / row_max

    plt.figure(figsize=(18, 12))
    sns.heatmap(
        activity_matrix_norm, cmap='YlOrRd', cbar_kws={'label': 'Normalized K-mer Activity'},
        xticklabels=top_motifs_list, yticklabels=[f'Z{i}' for i in range(num_z_dims)],
        linewidths=0.5, linecolor='gray'
    )
    plt.title(f'{protein_name} — Motif Activity Patterns Across Latent Dimensions', fontweight='bold', pad=20)
    plt.xlabel('Top RBP-Specific Motifs'); plt.ylabel('Latent Dimensions (Z)')
    plt.xticks(rotation=45, ha='right', fontsize=9)
    plt.tight_layout()
    plt.savefig(os.path.join(save_path, f'{protein_name}_motif_activity_heatmap.jpg'), dpi=300, bbox_inches='tight')
    plt.close()


def save_rbp_motif_report(rbp_scores, save_path, protein_name, metadata=None):
    sorted_motifs = sorted(rbp_scores.items(), key=lambda x: x[1]['rbp_final_score'], reverse=True)

    report_file = os.path.join(save_path, f'{protein_name}_rbp_specific_motif_report.txt')
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(f"RBP-Specific Motif Evaluation Report — {protein_name}\n")
        f.write("=" * 100 + "\n\n")
        f.write("Methodology:\n")
        if metadata:
            f.write(f"  - Background source: {metadata.get('background_source', 'unknown')} "
                    f"(n={metadata.get('n_background_sequences', 'NA')})\n")
            f.write(f"  - Accessibility source: {metadata.get('accessibility_source', 'unknown')} "
                    f"(real_icshape={metadata.get('n_real_icshape_used', 'NA')}, "
                    f"computational_fold={metadata.get('n_computational_fold_used', 'NA')}, "
                    f"failed={metadata.get('n_failed', 'NA')}, total={metadata.get('total', 'NA')})\n")
        else:
            f.write("  - Background: Dinucleotide-shuffled sequences (5x per peak)\n")
            f.write("  - Accessibility: ViennaRNA computational fold\n")
        f.write("  - Enrichment: Fisher's Exact Test (one-tailed) + Benjamini-Hochberg FDR correction\n")
        f.write("  - Significance threshold: q-value < 0.05\n")
        f.write("  - Centrality: Normalized distance to CLIP peak center\n")
        f.write("  - Final Score: 0.5*Enrichment_norm + 0.3*Accessibility + 0.2*Centrality\n")
        f.write("\n" + "=" * 100 + "\n\n")
        f.write(f"{'Motif':<12} | {'RBP_Score':>10} | {'P-value':>10} | {'Q-value':>10} | "
                f"{'FDR<0.05':>10} | {'Acc':>6} | {'Cent':>6}\n")
        f.write("-" * 110 + "\n")
        for kmer, scores in sorted_motifs[:50]:
            fdr_sig = "Y" if scores['enrichment_qval'] < 0.05 else " "
            f.write(f"{kmer:<12} | {scores['rbp_final_score']:>10.4f} | {scores['enrichment_pval']:>10.2e} "
                    f"| {scores['enrichment_qval']:>10.2e} | {fdr_sig:^10} | "
                    f"{scores['accessibility']:>6.3f} | {scores['centrality']:>6.3f}\n")
    print(f"  Motif report saved to {report_file}")

    csv_file = os.path.join(save_path, f'{protein_name}_rbp_motif_scores.csv')
    with open(csv_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Motif', 'RBP_Final_Score', 'Enrichment_Pval', 'Enrichment_Qval',
                          'Enrichment_Norm', 'Accessibility', 'Centrality', 'FDR_Significant'])
        for kmer, scores in sorted_motifs:
            fdr_sig = scores['enrichment_qval'] < 0.05
            writer.writerow([kmer, scores['rbp_final_score'], scores['enrichment_pval'],
                              scores['enrichment_qval'], scores['enrichment_norm'],
                              scores['accessibility'], scores['centrality'], fdr_sig])
    print(f"  Full motif CSV saved to {csv_file}")
    return csv_file


# ============================================================================
# Output storage (local or Google Drive when run in Colab)
# ============================================================================

def setup_output_root(drive_subfolder="DiRAMotif_results", prefer_drive=True):
    if prefer_drive:
        try:
            from google.colab import drive  # noqa: F401
            drive.mount('/content/drive', force_remount=False)
            output_root = f'/content/drive/MyDrive/{drive_subfolder}'
            os.makedirs(output_root, exist_ok=True)
            print(f"Google Drive mounted. Results will be saved to:\n   {output_root}")
            return output_root
        except ImportError:
            pass

    output_root = f'./{drive_subfolder}'
    os.makedirs(output_root, exist_ok=True)
    print(f"Results will be saved locally to: {os.path.abspath(output_root)}")
    return output_root


# ============================================================================
# Section 9: Full pipeline for a single protein
# ============================================================================

def run_full_pipeline_for_protein(protein_name, train_fasta, test_fasta,
                                    negative_fasta=None, icshape_json=None,
                                    k=6, hidden_dim=200, latent_dim=30, epochs=100,
                                    dropout_rate=DROPOUT_RATE,
                                    run_sensitivity=True, run_multi_k=False,
                                    attract_meme_file=None,
                                    pwm_max_mismatches=PWM_MAX_MISMATCHES,
                                    pwm_pseudocount_scale=PWM_PSEUDOCOUNT_SCALE,
                                    pwm_center_window_fraction=PWM_CENTER_WINDOW_FRACTION,
                                    pwm_min_info_content=PWM_MIN_INFO_CONTENT,
                                    output_root="./rna_motif_results"):

    save_path = os.path.join(output_root, protein_name)
    os.makedirs(save_path, exist_ok=True)
    print(f"\n{'='*90}\nProcessing protein: {protein_name}\n{'='*90}")

    check_sequence_length_diagnostics(train_fasta)
    check_sequence_length_diagnostics(test_fasta)

    train_records = load_fasta_records(train_fasta)
    test_records = load_fasta_records(test_fasta)
    train_ids = [r[0] for r in train_records]
    train_sequences = [r[1] for r in train_records]
    test_sequences = [r[1] for r in test_records]
    print(f"  Number of sequences - train: {len(train_sequences)} | test: {len(test_sequences)}")

    negative_sequences = None
    if negative_fasta is not None and os.path.exists(negative_fasta):
        negative_sequences = load_fasta_sequences(negative_fasta)
        print(f"  Number of real negative sequences: {len(negative_sequences)}")
    else:
        print("  No negative-set file available; falling back to dinucleotide shuffle.")

    real_icshape = load_icshape_scores(icshape_json) if icshape_json else {}
    if real_icshape:
        print(f"  Number of records with real icSHAPE scores: {len(real_icshape)}")
    else:
        print("  No icSHAPE file available; falling back to ViennaRNA computational folding.")

    X_train, kmer_dict = extract_rna_kmer_features_with_shared_dict(train_sequences, k=k)
    X_test, _ = extract_rna_kmer_features_with_shared_dict(test_sequences, k=k, kmer_dict=kmer_dict)
    input_dim = X_train.shape[1]
    print(f"  Feature space dimensionality (k={k}): {input_dim}")

    print(f"  Training main model (dropout={dropout_rate}) ...")
    model, history, train_loader, test_loader = train_vae_with_real_holdout(
        X_train, X_test, input_dim, hidden_dim, latent_dim, epochs=epochs, dropout_rate=dropout_rate
    )
    torch.save(model.state_dict(), os.path.join(save_path, f'{protein_name}_model_weights.pth'))
    plot_loss_curves(history, save_path, protein_name)

    with open(os.path.join(save_path, f'{protein_name}_loss_history.json'), 'w') as f:
        json.dump(history, f, indent=2)

    all_z_train = extract_all_z_values(model, train_loader)
    all_z_test = extract_all_z_values(model, test_loader)

    metrics_train = calculate_vae_metrics(all_z_train, model, train_loader)
    metrics_test = calculate_vae_metrics(all_z_test, model, test_loader)

    with open(os.path.join(save_path, f'{protein_name}_vae_metrics_train.json'), 'w') as f:
        json.dump(metrics_train, f, indent=2)
    with open(os.path.join(save_path, f'{protein_name}_vae_metrics_test.json'), 'w') as f:
        json.dump(metrics_test, f, indent=2)

    print(f"  [Train] Sparsity={metrics_train['sparsity']:.4f}, "
          f"ActiveUnitsRatio={metrics_train['active_units_ratio']:.4f}")
    print(f"  [Test ] Sparsity={metrics_test['sparsity']:.4f}, "
          f"ActiveUnitsRatio={metrics_test['active_units_ratio']:.4f}")

    plot_diagnostic_figures(all_z_train, X_train, model, train_loader, save_path, protein_name)

    print("  Extracting candidate motifs from the latent space (train) ...")
    top_kmers = get_top_kmers_per_z(all_z_train, X_train, kmer_dict, train_sequences, k=k, top_n=30)
    all_candidate_kmers = []
    for z_dim, data in top_kmers.items():
        for kmer, count in data['kmers']:
            if kmer not in all_candidate_kmers:
                all_candidate_kmers.append(kmer)
    print(f"  Total number of candidate motifs: {len(all_candidate_kmers)}")

    print("  Scoring motifs biologically (enrichment + accessibility + centrality) ...")
    rbp_scores, postproc_meta = rbp_specific_postprocessing(
        all_candidate_kmers, train_sequences,
        peak_ids=train_ids, real_icshape=real_icshape,
        real_negative_seqs=negative_sequences
    )
    csv_path = save_rbp_motif_report(rbp_scores, save_path, protein_name, metadata=postproc_meta)

    sorted_rbp_motifs = sorted(rbp_scores.items(), key=lambda x: x[1]['rbp_final_score'], reverse=True)
    top_15_motifs = [kmer for kmer, _ in sorted_rbp_motifs[:15]]
    plot_motif_activity_heatmap(top_kmers, top_15_motifs, save_path, protein_name)

    # Biologically grounded PWM construction for all candidate motifs in the CSV
    print("  Building biologically grounded PWMs (non-overlapping occurrences, "
          "relative pseudocount, centrality filter) for all candidate motifs ...")
    motif_pwm_dict, meme_path, bg_path = build_and_export_all_motif_pwms(
        rbp_scores, train_sequences, save_path, protein_name,
        max_mismatches=pwm_max_mismatches,
        pseudocount_scale=pwm_pseudocount_scale,
        center_window_fraction=pwm_center_window_fraction,
        min_info_content=pwm_min_info_content,
    )

    tomtom_summary = None
    if attract_meme_file is not None:
        tomtom_summary = run_tomtom_comparison(
            meme_path, attract_meme_file, save_path, protein_name,
            background_file=bg_path,
            motif_len_for_overlap=k,
        )
    else:
        print("  No attract_meme_file provided; skipping Tomtom comparison step.")

    sensitivity_df = None
    if run_sensitivity:
        sensitivity_df = run_latent_dim_sensitivity(
            X_train, X_test, input_dim, hidden_dim, save_path, protein_name
        )

    table5_df = None
    if run_multi_k:
        table5_df, _ = run_multi_k_robustness_analysis(
            train_sequences, test_sequences, save_path, protein_name,
            hidden_dim=hidden_dim, latent_dim=latent_dim, epochs=epochs
        )

    # Save the full run configuration
    config = {
        "protein": protein_name,
        "k": k,
        "input_dim": input_dim,
        "hidden_dim": hidden_dim,
        "latent_dim": latent_dim,
        "epochs": epochs,
        "batch_size": 128,
        "learning_rate": 1e-3,
        "weight_decay": 1e-5,
        "optimizer": "Adam",
        "gradient_clip_max_norm": 5.0,
        "dirichlet_prior_alpha": 0.1,
        "encoder_architecture": "Linear(input_dim,hidden_dim) -> ReLU -> LayerNorm -> Dropout -> Linear(hidden_dim,latent_dim) -> Softmax(alpha)",
        "decoder_architecture": "Linear(latent_dim,hidden_dim) -> ReLU -> LayerNorm -> Dropout -> Linear(hidden_dim,input_dim) -> Sigmoid",
        "normalization": "LayerNorm (encoder and decoder)",
        "dropout": dropout_rate,
        "device": str(DEVICE),
        "active_unit_variance_threshold": ACTIVE_UNIT_VARIANCE_THRESHOLD,
        "sparsity_near_zero_threshold": SPARSITY_NEAR_ZERO_THRESHOLD,
        "n_train_sequences": len(train_sequences),
        "n_test_sequences": len(test_sequences),
        "train_test_source": "separate pre-split FASTA files (independent holdout, not an artificial split)",
        "final_score_formula": "0.5*Enrichment_norm + 0.3*Accessibility + 0.2*Centrality",
        "run_sensitivity_analysis": run_sensitivity,
        "run_multi_k_robustness_analysis": run_multi_k,
        "tomtom_comparison_run": tomtom_summary is not None,
        # PWM construction settings
        "pwm_construction_method": "non_overlapping_greedy_best_hit_first_with_centrality_filter",
        "pwm_max_mismatches": pwm_max_mismatches,
        "pwm_pseudocount_scale": pwm_pseudocount_scale,
        "pwm_min_pseudocount": PWM_MIN_PSEUDOCOUNT,
        "pwm_center_window_fraction": pwm_center_window_fraction,
        "pwm_min_info_content_filter": pwm_min_info_content,
        "pwm_built_for_all_candidate_motifs": True,
        "n_motifs_with_pwm": len(motif_pwm_dict),
        "n_total_candidate_motifs": len(all_candidate_kmers),
        # Tomtom settings
        "tomtom_small_sample_correction": "enabled",
        "tomtom_min_overlap": max(k - 1, 4),
        "tomtom_background_file_used": bg_path,
        # Data sources
        "negative_fasta_used": negative_fasta if negative_sequences is not None else None,
        "icshape_json_used": icshape_json if real_icshape else None,
        **postproc_meta,
    }
    with open(os.path.join(save_path, f'{protein_name}_run_config.json'), 'w') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"Finished processing {protein_name}. All outputs saved to: {os.path.abspath(save_path)}")

    return {
        'protein': protein_name,
        'n_train': len(train_sequences),
        'n_test': len(test_sequences),
        'train_reconstruction_error': metrics_train['reconstruction_error_mean'],
        'test_reconstruction_error': metrics_test['reconstruction_error_mean'],
        'train_sparsity': metrics_train['sparsity'],
        'test_sparsity': metrics_test['sparsity'],
        'train_active_units_ratio': metrics_train['active_units_ratio'],
        'test_active_units_ratio': metrics_test['active_units_ratio'],
        'n_candidate_motifs': len(all_candidate_kmers),
        'n_motifs_with_pwm': len(motif_pwm_dict),
        'top_motif': sorted_rbp_motifs[0][0] if sorted_rbp_motifs else None,
        'top_motif_score': sorted_rbp_motifs[0][1]['rbp_final_score'] if sorted_rbp_motifs else None,
        'tomtom_agreement_pct': tomtom_summary['tomtom_agreement_pct'] if tomtom_summary else None,
        'background_source': postproc_meta.get('background_source'),
        'accessibility_source': postproc_meta.get('accessibility_source'),
        'n_real_icshape_used': postproc_meta.get('n_real_icshape_used'),
        'dropout_rate': dropout_rate,
    }


# ============================================================================
# Section 10: Discovering train/test/negative/icSHAPE file sets and batch execution
# ============================================================================

def discover_protein_dataset_pairs(data_dir=DEFAULT_DATA_DIR,
                                    train_suffix=TRAIN_SUFFIX, test_suffix=TEST_SUFFIX,
                                    negative_suffix=NEGATIVE_SUFFIX, icshape_suffix=ICSHAPE_SUFFIX):
    train_files = glob.glob(os.path.join(data_dir, f"*{train_suffix}"))
    pairs = {}
    for train_path in train_files:
        base = os.path.basename(train_path)
        protein_name = base[: -len(train_suffix)]
        test_path = os.path.join(data_dir, f"{protein_name}{test_suffix}")
        if not os.path.exists(test_path):
            print(f"Warning: test file for {protein_name} not found ({test_path}); skipping this protein.")
            continue
        negative_path = os.path.join(data_dir, f"{protein_name}{negative_suffix}")
        icshape_path = os.path.join(data_dir, f"{protein_name}{icshape_suffix}")
        pairs[protein_name] = {
            'train': train_path,
            'test': test_path,
            'negative': negative_path if os.path.exists(negative_path) else None,
            'icshape': icshape_path if os.path.exists(icshape_path) else None,
        }
    return pairs


def run_batch_pipeline(data_dir=DEFAULT_DATA_DIR, output_root="./rna_motif_results",
                        k=6, hidden_dim=200, latent_dim=30, epochs=100,
                        dropout_rate=DROPOUT_RATE,
                        run_sensitivity_for_all=False, sensitivity_subset_size=5,
                        run_multi_k_for_all=False, multi_k_subset_size=5,
                        attract_meme_file=None,
                        pwm_max_mismatches=PWM_MAX_MISMATCHES,
                        pwm_pseudocount_scale=PWM_PSEUDOCOUNT_SCALE,
                        pwm_center_window_fraction=PWM_CENTER_WINDOW_FRACTION,
                        pwm_min_info_content=PWM_MIN_INFO_CONTENT,
                        priority_sensitivity_proteins=None):
    os.makedirs(output_root, exist_ok=True)
    pairs = discover_protein_dataset_pairs(data_dir)
    print(f"\nNumber of protein/cell-line datasets found (both train and test present): {len(pairs)}")
    n_with_negative = sum(1 for p in pairs.values() if p['negative'] is not None)
    n_with_icshape = sum(1 for p in pairs.values() if p['icshape'] is not None)
    print(f"   With real negative-set file: {n_with_negative}/{len(pairs)}")
    print(f"   With real icSHAPE file: {n_with_icshape}/{len(pairs)}")

    protein_names = list(pairs.keys())

    sensitivity_targets = set(protein_names)
    if not run_sensitivity_for_all and len(protein_names) > sensitivity_subset_size:
        priority = set(priority_sensitivity_proteins or []) & set(protein_names)
        remaining_slots = max(0, sensitivity_subset_size - len(priority))
        others = [p for p in protein_names if p not in priority]
        random.shuffle(others)
        sensitivity_targets = priority | set(others[:remaining_slots])
        print(f"   (latent_dim sensitivity analysis limited to {len(sensitivity_targets)} proteins: "
              f"{sorted(sensitivity_targets)})")

    multi_k_targets = set(protein_names)
    if not run_multi_k_for_all and len(protein_names) > multi_k_subset_size:
        shuffled = protein_names.copy()
        random.shuffle(shuffled)
        multi_k_targets = set(shuffled[:multi_k_subset_size])
        print(f"   (multi-k robustness analysis [Table 5] limited to {multi_k_subset_size} sampled proteins: "
              f"{sorted(multi_k_targets)})")

    summary_rows = []
    for protein_name, paths in pairs.items():
        try:
            result = run_full_pipeline_for_protein(
                protein_name, paths['train'], paths['test'],
                negative_fasta=paths['negative'], icshape_json=paths['icshape'],
                k=k, hidden_dim=hidden_dim, latent_dim=latent_dim, epochs=epochs,
                dropout_rate=dropout_rate,
                run_sensitivity=(protein_name in sensitivity_targets),
                run_multi_k=(protein_name in multi_k_targets),
                attract_meme_file=attract_meme_file,
                pwm_max_mismatches=pwm_max_mismatches,
                pwm_pseudocount_scale=pwm_pseudocount_scale,
                pwm_center_window_fraction=pwm_center_window_fraction,
                pwm_min_info_content=pwm_min_info_content,
                output_root=output_root
            )
            summary_rows.append(result)
        except Exception as e:
            print(f"Error processing {protein_name}: {e}")
            continue

    summary_df = pd.DataFrame(summary_rows)
    summary_path = os.path.join(output_root, "summary_all_proteins.csv")
    summary_df.to_csv(summary_path, index=False)
    print(f"\n{'='*90}\nFinal summary for all proteins saved to {summary_path}")
    print(f"Total proteins processed successfully: {len(summary_df)}")
    if len(summary_df) > 0:
        print(f"Proteins that used a real negative-set background: "
              f"{(summary_df['background_source'] == 'real_non_enriched_clip_background (experimentally derived negative set)').sum()}")
        print(f"Proteins that used (at least partially) real icSHAPE data: "
              f"{(summary_df['n_real_icshape_used'].fillna(0) > 0).sum()}")
        print(f"Mean number of motifs with a PWM per protein: "
              f"{summary_df['n_motifs_with_pwm'].mean():.1f}")
    print(f"{'='*90}")
    return summary_df


# ============================================================================
# Entry point
# ============================================================================
if __name__ == "__main__":
    DATA_DIR = "/content/data"
    OUTPUT_ROOT = setup_output_root(drive_subfolder="DiRAMotif_results", prefer_drive=True)
    ATTRACT_MEME_FILE = None  # path to the converted ATtRACT MEME file, if available

    PRIORITY_SENSITIVITY_PROTEINS = [
        "AGO2_HEK293", "AGO2_HeLa", "EIF4A3_HEK293", "U2AF2_HepG2", "HNRNPC_HeLa",
    ]

    summary = run_batch_pipeline(
        data_dir=DATA_DIR,
        output_root=OUTPUT_ROOT,
        k=6,
        hidden_dim=200,
        latent_dim=30,
        epochs=100,
        dropout_rate=DROPOUT_RATE,
        run_sensitivity_for_all=False,
        sensitivity_subset_size=5,
        run_multi_k_for_all=False,
        multi_k_subset_size=5,
        attract_meme_file=ATTRACT_MEME_FILE,
        pwm_max_mismatches=PWM_MAX_MISMATCHES,
        pwm_pseudocount_scale=PWM_PSEUDOCOUNT_SCALE,
        pwm_center_window_fraction=PWM_CENTER_WINDOW_FRACTION,
        pwm_min_info_content=PWM_MIN_INFO_CONTENT,
        priority_sensitivity_proteins=PRIORITY_SENSITIVITY_PROTEINS,
    )

    print("\nSample of results summary:")
    print(summary.head(10))